Add golfer page - frontend
cristian-scarisoreanu/golfr_frontend pull request #1
Opened 2022-02-20 17:24 UTC by cristian-scarisoreanu

### Fixes: [Add golfer page](https://github.com/GeorgeMarcus/golfr_frontend/issues/1)

### Changes

- Changed the `Layout` to render using a given id, which is used to create a link to the page of the logged-in golfer.
- Added a link to the home page by wrapping the _Home_ text in a `Link` component.
- Changed the `ScoreCard` by adding a link to every golfer's page.
- Added `/lib/useUserScores` to fetch a golfer's name and scores from the backend (using the specific API URL).
- Added the golfer page `pages/golfer/[id]` which displays the golfer's name, the number of scores he has, and a list of all of his scores ordered by date. On this page, the `ScorePostWidget` will only render for the logged-in user.

### Before

**Hompage (scores feed)**

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/98027233/154854623-7b029787-7d54-4ac0-9308-893e8cfd8c89.png">

**Golfer page**

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/98027233/154854655-c958e70b-7ab9-4133-94ec-27de651802ef.png">

### After

**Hompage (scores feed)**

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/98027233/154854481-15a944a8-f957-4ee1-9f47-ef9ee857153f.png">

**Page of the logged-in golfer**

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/98027233/154854495-04e68b65-57d9-46c3-8a35-ee10f3d89f42.png">

**Page of a golfer with scores**

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/98027233/154854515-a7c3e154-e0dc-4529-85c4-76ac62d311c6.png">

**Page of a golfer with no scores**

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/98027233/154854544-0d737509-4515-40f6-9c8c-21f30ba2b6a1.png">

**Page of a nonexistent golfer/user**

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/98027233/154854565-3d08ddb4-02fa-4148-893d-2524dc633eeb.png">

2022-02-20 20:37 UTC, SergiuApostuTOL requested changes

2022-02-20 20:37 UTC, SergiuApostuTOL commented on components/ScoreCard.js
> +          )}
Avoid calling a hook multiple times if you don't need too.

Move the result of `useRouter()` to a constant/variable and use that one to get the path name.

2022-02-20 20:37 UTC, SergiuApostuTOL commented on lib/useUserScores
> +import useSWR from 'swr'
This file has no extension 😄

2022-02-20 20:37 UTC, SergiuApostuTOL commented on components/Layout.js
> +const Layout = ({ children, id }) => {
Why do we need to receive the `id` from the parent? In both of the cases where we are using Layout, id is set to `getUserId()`. I think we can just call that method inside this component.

2022-02-20 20:37 UTC, SergiuApostuTOL commented on pages/golfers/[id].js
> +  } else { return null }
It's hard to see `return null` at the end of the file after many lines of JSX. Usually, this cases are handled earlier.

```js
if (!userId) {
  return null
}

return (
  <Layout>
    ...
  </Layout>
)
```

2022-02-20 20:37 UTC, SergiuApostuTOL commented on pages/index.js
> +  if (scores || error) {
Why are we displaying this page only if there are scores or there is an error?

2022-02-21 09:03 UTC, cristian-scarisoreanu commented on components/Layout.js
> +const Layout = ({ children, id }) => {
I've added a custom hook to set the `userId` to the result of `getUserId()` method. In this way I will not get an error by calling `getUserId()` directly in the `Layout` component . (local storage is not defined)

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/98027233/154922312-d0fc174f-df16-4576-bebc-26e913fd8c07.png">

2022-02-21 10:39 UTC, SergiuApostuTOL approved these changes

2022-02-21 10:39 UTC, merged